### ISSUE TITLE
Make CLI option shortcuts more predictable

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/ProtoData#162]
Some of the CLI options have shortcut forms. For instance, `--renderer` is `-r` and `--source-root` is `--src`. However, some of the shortcuts are less intuitive, such as `-t` for `--request`.

We should make the option shortcuts more intuitive.

This might be an API breaking change, so it should be treated with caution.

**Comment by alexander-yevsyukov** [comment]
@armiol, assuming we agreed to have a YAML configuration file instead of a bunch of shortcuts, this issue is going to be resolved by itself.

@dmdashenkov, I could not find an issue on YAML. Please link this one to that one.

**Comment by alexander-yevsyukov** [comment]
Closing as outdated since options were reworked significantly recently.
