### ISSUE TITLE
Improve the name of `TypeSystem.from(Querying)`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/ProtoData#163]
The method `TypeSystem.from()` is typically used by `Renderer`s. So the usage looks like this:

```kotlin
val typeSystem = TypeSystem.from(this)
```

It does not read well because we do not create a `TypeSystem` from rendering. We create it "for" rendering. Obviously, we cannot use `for` as it is a reserved word. But `from` isn't a good replacement because it's confusing.

Let's have a more meaningful name. How about having it like this:

```kotlin
val typeSystem = TypeSystem.serving(this)
```

**Comment by alexander-yevsyukov** [comment]
@armiol, FYI.

**Comment by armiol** [comment]
I second `serving`, as it will play with the rest of the signature.

**Comment by armiol** [comment]
@dmdashenkov WDYT?
