### ISSUE TITLE
The name `GeneratedDeclaration` is not always applicable

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/ProtoData#167]
Consider `JavaRejectionConvention` class. Its method `declarationFor()` returns `GeneratedDeclaration<Java, ClassName>`.

At the time of calling this method a class extending `RejectionThrowable` is not yet generated.

We need a more suitable name.

**Comment by alexander-yevsyukov** [comment]
@armiol, @dmdashenkov, let's discuss.

**Comment by alexander-yevsyukov** [comment]
To me `Declaration` would be quite enough.

**Comment by dmdashenkov** [comment]
Addressed in a recent PR.
