### ISSUE TITLE
Set a correct description for `io.spine.protodata.protodata-fat-cli` artifact

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/ProtoData#273]
We assemble `protodata-fat-cli` artifact from many source JARs. Therefore, in the resulting fat JAR, one of the metadata fields is apparently copied from some Google library, causing [the description of our artifact](https://github.com/SpineEventEngine/ProtoData/packages/1215911) to read 

```
PROTO library for proto-google-common-protos
```
which it is obviously not.

In scope of this issue we should put a proper description instead of the current one.

**Comment by alexander-yevsyukov** [comment]
Removed the wrong description via manual editing in GitHub.
