### ISSUE TITLE
Remove deprecated properties

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/ProtoData#74]
Since `0.2.8`, there are deprecated properties in the Gradle plugin: `Extension.subDir`, `LaunchProtoData.source`, and `LaunchProtoData.target`.

Those are kept there for compatibility reasons.

We should delete them soon. Probably, such a change should trigger a minor version increase (i.e. to `0.3.0`).

**Comment by alexander-yevsyukov** [comment]
Addressed by #136.
