### ISSUE TITLE
Revisit "C-like"ness of languages

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/ProtoData#8]
For now, we have declared that Java, Kotlin, and JavaScript are "C-like" languages. Like any human-made category, "C-like" is a made up concept which is helpful in some cases but not in others [citation needed].

We should probably revisit the name of the class `CLike`, it might be too broad.

**Comment by alexander-yevsyukov** [comment]
Programming languages are also human-made. Let's drop the category. JavaScript is way too distant from Kotlin. One of the common things is curly braces. But it doesn't sound like a sound basis for gathering languages.

**Comment by alexander-yevsyukov** [comment]
As suggested in #10, how about naming them `Curly`? cc: @armiol
