### ISSUE TITLE
Add inline insertion points

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/ProtoData#84]
When working on annotating method return type values in [this PR in `validation`](https://github.com/SpineEventEngine/validation/pull/54) I've faced the limitation of the current insertion mechanism: it does not allow to add the code inside existing line.

The thing is that type annotation of a method return value must be placed before the short type name. Like this:

```java
@java.lang.Override
    public io.spine.validation.test.money. @io.spine.validate.Validated AlwaysValidTime build() {
```

It cannot be done like this:
```java
    @io.spine.validate.Validated  // WON'T WORK: the Java compiler won't accept this.
    @java.lang.Override
    public io.spine.validation.test.money.AlwaysValidTime build() {
```

Because of this we need a mechanism that would allow inserting (or even replacing) the code inside existing lines.

**Comment by alexander-yevsyukov** [comment]
In the Chat discussion, @armiol suggested to have API for updating method signatures, instead of inline insertion points. It would be easier to understand.

It may be easier to understand, but it would make ProtoData not a language neutral tool. So far it looks like it does not know much about the languages it serves. @dmdashenkov, do you agree?

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, fixed?

**Comment by dmdashenkov** [comment]
Yeap.
